export { default as LayoutPokemon } from './LayoutPokemon.vue'
export { default as HeaderPokemon } from './HeaderPokemon.vue'
export { default as OptionsPokemon } from './OptionsPokemon.vue'
export { default as PicturePokemon } from './PicturePokemon.vue'
export { default as FooterPokemon } from './FooterPokemon.vue'
export { default as CountPokemon } from './CountPokemon.vue'
export { default as BtnPlayAgain } from './ButtonPlayAgain.vue'